# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaturant_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaturant',
            new_name='Restaurant',
        ),
    ]
