# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantlocation_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='categories',
            new_name='category',
        ),
    ]
